CREATE TABLE IF NOT EXISTS USER_SESSIONS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mobileNo VARCHAR(20) NOT NULL,
  refreshToken VARCHAR(255) NOT NULL,
  expiresAt DATETIME NOT NULL,
  deviceInfo VARCHAR(255),
  ipAddress VARCHAR(45),
  queryString VARCHAR(255),
  ohaUserId VARCHAR(100),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_mobile_refresh (mobileNo, refreshToken)
);
